/* Max Learning Lab games — original canvas / DOM games. No dependencies. */
(function () {
  'use strict';
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const shuffle = a => { const b = a.slice(); for (let i = b.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [b[i], b[j]] = [b[j], b[i]]; } return b; };
  function el(tag, cls, text) { const n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; }
  function button(text, cls) { const n = el('button', 'game-button ' + (cls || ''), text); n.type = 'button'; return n; }
  function createScope(container, api) {
    const root = el('section', 'game-shell'); container.appendChild(root);
    const clean = []; let dead = false;
    const on = (target, type, fn, options) => { target.addEventListener(type, fn, options); clean.push(() => target.removeEventListener(type, fn, options)); };
    const safeApi = { get: (k, d) => { try { return api && api.get ? api.get(k, d) : d; } catch (_) { return d; } }, set: (k, v) => { try { if (api && api.set) api.set(k, v); } catch (_) {} }, award: (k, v) => { if (api && api.award) api.award(k, v); }, read: t => { if (api && api.read) api.read(t); } };
    return { root, on, clean, api: safeApi, alive: () => !dead, dispose() { dead = true; clean.forEach(fn => fn()); root.remove(); } };
  }
  function intro(s, kicker, title, help) {
    const row = el('div', 'game-intro'), text = el('div'); text.append(el('p', 'game-kicker', kicker), el('h2', 'game-title', title), el('p', 'game-help', help)); row.append(text); s.root.append(row); return row;
  }
  function stat(label, value) { const outer = el('div', 'game-stat'), number = el('strong', 'game-stat-value', value); outer.append(el('span', 'game-stat-label', label), number); return { outer, number }; }
  function feedback() { const root = el('div', 'game-feedback'), title = el('p', 'game-feedback-title'), text = el('p', 'game-feedback-text'); root.setAttribute('role', 'status'); root.setAttribute('aria-live', 'polite'); root.setAttribute('aria-atomic', 'true'); root.append(title, text); return { root, title, text }; }
  function setupCanvas(s, canvas, aspect, redraw) {
    const ctx = canvas.getContext('2d'); let width = 800, height = width / aspect;
    function resize() { const rect = canvas.getBoundingClientRect(); width = Math.max(100, rect.width || 800); height = Math.max(100, rect.height || width / aspect); const dpr = Math.min(2, window.devicePixelRatio || 1); canvas.width = Math.round(width * dpr); canvas.height = Math.round(height * dpr); ctx.setTransform(dpr, 0, 0, dpr, 0, 0); redraw(); }
    if (typeof ResizeObserver !== 'undefined') { const ro = new ResizeObserver(resize); ro.observe(canvas); s.clean.push(() => ro.disconnect()); } else s.on(window, 'resize', resize);
    return { ctx, resize, get w() { return width; }, get h() { return height; } };
  }
  function path(ctx, points, fill, stroke, lineWidth) { ctx.beginPath(); points.forEach((p, i) => i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1])); ctx.closePath(); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lineWidth || 1; ctx.stroke(); } }
  function circle(ctx, x, y, radius, fill, stroke) { ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.stroke(); } }
  function roundRect(ctx, x, y, w, h, r, fill) { ctx.beginPath(); if (ctx.roundRect) ctx.roundRect(x, y, w, h, r); else ctx.rect(x, y, w, h); ctx.fillStyle = fill; ctx.fill(); }

  // HOME RUN HERO: one pitch, one decision. Hits advance every runner equally.
  function baseball(s) {
    s.root.classList.add('game-baseball');
    intro(s, 'Timing + counting', 'Home Run Hero', 'Tap Pitch. Watch the ball come closer. Tap SWING when the timing dot reaches the bright gold zone!');
    const options = el('div', 'game-action-row'), tabs = el('div', 'game-tabs'), practice = button('Practice'), regular = button('3-out game');
    [practice, regular].forEach(b => b.className = 'game-tab'); tabs.append(practice, regular); const read = button('Hear instructions', 'game-muted-button'); options.append(tabs, read); s.root.append(options);
    let mode = 'practice', phase = 'ready', score = 0, strikes = 0, outs = 0, bases = [false, false, false], hits = 0, homers = 0, pitchT = 0, pitchElapsed = 0, flightElapsed = 0, swingStamp = 0, swingHit = false, paused = false, lastTime = null, raf = 0, resultRuns = 0, best = Number(s.api.get('baseball-best', 0)) || 0;
    const stats = el('div', 'game-stats'), runStat = stat('Runs', 0), strikeStat = stat('Strikes', '0 / 3'), outStat = stat('Outs', 'Practice'), bestStat = stat('Best game', best); [runStat, strikeStat, outStat, bestStat].forEach(x => stats.append(x.outer)); s.root.append(stats);
    const stage = el('div', 'game-stage'), canvas = el('canvas', 'game-canvas'); canvas.setAttribute('aria-label', 'Baseball diamond. Use the Pitch and Swing buttons below.'); canvas.setAttribute('role', 'img'); stage.append(canvas); s.root.append(stage);
    const meterWrap = el('div'), meter = el('div', 'game-pitch-meter'), zone = el('div', 'game-pitch-zone'), sweet = el('div', 'game-pitch-sweet'), dot = el('div', 'game-pitch-dot'); meter.setAttribute('aria-hidden', 'true'); meter.append(zone, sweet, dot); const labels = el('div', 'game-meter-labels'); labels.append(el('span', '', 'Pitcher'), el('span', '', 'Gold zone = swing')); meterWrap.append(meter, labels); s.root.append(meterWrap);
    const fb = feedback(); s.root.append(fb.root); const controls = el('div', 'game-controls'), pitch = button('Pitch', 'game-primary game-big-button'), swing = button('SWING!', 'game-gold game-big-button'), pause = button('Pause'); controls.append(pitch, swing, pause); const keyboardHint = el('p', 'game-keyboard-hint', 'Keyboard: Space to pitch or swing · P to pause'); s.root.append(controls, keyboardHint);
    s.root.append(el('p', 'game-footer-note', 'Our simple rules: a single moves everyone 1 base, a double 2, and a triple 3. A home run brings everyone home. A foul never adds strike 3.'));
    // Keep the ball, timing guide, and swing control together within the tablet viewport.
    const playLayout = el('div', 'game-baseball-layout'), fieldColumn = el('div', 'game-baseball-field'), controlColumn = el('div', 'game-baseball-sidebar');
    options.classList.add('game-baseball-options'); stats.classList.add('game-baseball-stats'); stage.classList.add('game-baseball-stage'); meterWrap.classList.add('game-baseball-meter'); controls.classList.add('game-baseball-controls'); fb.root.classList.add('game-baseball-feedback');
    s.root.insertBefore(playLayout, options); fieldColumn.append(stage, meterWrap); controlColumn.append(options, stats, controls, fb.root, keyboardHint); playLayout.append(fieldColumn, controlColumn);
    let view;
    function announce(title, text) { fb.title.textContent = title; fb.text.textContent = text; }
    function update() { runStat.number.textContent = score; strikeStat.number.textContent = strikes + ' / 3'; outStat.number.textContent = mode === 'practice' ? 'Practice' : outs + ' / 3'; bestStat.number.textContent = best; practice.setAttribute('aria-pressed', mode === 'practice'); regular.setAttribute('aria-pressed', mode === 'game'); pitch.disabled = paused || phase === 'pitching' || phase === 'flight'; pitch.textContent = phase === 'gameover' ? 'Play again' : 'Pitch'; swing.disabled = paused || phase !== 'pitching'; pause.textContent = paused ? 'Resume' : 'Pause'; pause.disabled = phase === 'ready' || phase === 'gameover'; practice.disabled = phase === 'pitching' || phase === 'flight'; regular.disabled = practice.disabled; dot.style.left = clamp(pitchT / 1.15 * 100, 0, 99) + '%'; }
    function reset(nextMode) { if (nextMode) mode = nextMode; phase = 'ready'; score = strikes = outs = hits = homers = 0; bases = [false, false, false]; pitchT = pitchElapsed = flightElapsed = 0; paused = false; lastTime = null; swingStamp = 0; announce(mode === 'practice' ? 'Your batting practice starts here.' : 'Let’s play ball, Max!', mode === 'practice' ? 'Slower pitches. A wider hitting zone. Keep practicing as long as you like.' : 'You have 3 outs. How many runs can you bring home?'); stop(); update(); draw(); }
    function stop() { if (raf) cancelAnimationFrame(raf); raf = 0; lastTime = null; }
    function run() { if (!raf && !paused && !document.hidden && (phase === 'pitching' || phase === 'flight')) raf = requestAnimationFrame(frame); }
    function frame(time) { raf = 0; if (!s.alive() || paused || document.hidden) return; const dt = lastTime == null ? 0 : Math.min(time - lastTime, 80); lastTime = time; if (phase === 'pitching') { pitchElapsed += dt; pitchT = pitchElapsed / (mode === 'practice' ? 2450 : 1700); if (pitchT > 1.15) strike('Just a little late.', 'The ball reached the catcher. Try swinging when the dot is in gold.'); } else if (phase === 'flight') { flightElapsed += dt; if (flightElapsed >= 900) phase = 'ready'; } update(); draw(); run(); }
    function startPitch() { if (paused || phase === 'pitching' || phase === 'flight') return; if (phase === 'gameover') reset(); phase = 'pitching'; pitchElapsed = pitchT = 0; swingStamp = 0; swingHit = false; announce('Here comes the pitch…', 'Watch the dot travel toward the gold zone.'); update(); run(); }
    function strike(title, detail) { strikes++; phase = 'ready'; if (strikes >= 3) { strikes = 0; outs++; if (mode === 'game' && outs >= 3) { phase = 'gameover'; if (score > best) { best = score; s.api.set('baseball-best', best); } s.api.award('baseball-played', 'Ballpark explorer'); announce('Final score: ' + score + (score === 1 ? ' run!' : ' runs!'), hits + (hits === 1 ? ' hit' : ' hits') + ' and ' + homers + (homers === 1 ? ' home run. ' : ' home runs. ') + 'Want another game?'); } else announce(mode === 'practice' ? 'A fresh batter. Keep practicing!' : 'Strike 3. That’s ' + outs + (outs === 1 ? ' out.' : ' outs.'), mode === 'practice' ? 'Try the gold zone on your next pitch.' : 'Your runners stay on base. Tap Pitch when you’re ready.'); } else announce(title, detail + ' Strike ' + strikes + '.'); stop(); update(); draw(); }
    function hit(amount) { resultRuns = 0; const next = [false, false, false]; for (let i = 0; i < 3; i++) if (bases[i]) { if (i + amount >= 3) resultRuns++; else next[i + amount] = true; } if (amount === 4) resultRuns++; else next[amount - 1] = true; bases = next; score += resultRuns; hits++; strikes = 0; if (amount === 4) { homers++; s.api.award('baseball-homer', 'Home run hero'); } phase = 'flight'; flightElapsed = 0; swingHit = true; announce(['', 'Single!', 'Double!', 'Triple!', 'HOME RUN!'][amount], resultRuns ? resultRuns + (resultRuns === 1 ? ' runner made it home. ' : ' runners made it home. ') + 'Your total: ' + score + '.' : 'Your batter moves ' + amount + (amount === 1 ? ' base.' : ' bases.') + ' Keep the runners moving!'); update(); run(); }
    function swingBat() { if (paused || phase !== 'pitching') return; const error = Math.abs(pitchT - 1); swingStamp = performance.now(); const scale = mode === 'practice' ? 1.6 : 1; if (error <= .065 * scale) hit(4); else if (error <= .10 * scale) hit(3); else if (error <= .145 * scale) hit(2); else if (error <= .20 * scale) hit(1); else if (error <= .30 * scale) { phase = 'ready'; strikes = Math.min(2, strikes + 1); announce('Foul ball!', strikes === 2 ? 'You still have 2 strikes. A foul cannot be strike 3.' : 'The ball went outside the lines. Try the gold zone next time.'); stop(); update(); draw(); } else strike('An early swing.', 'Let the ball come a little closer.'); }
    function setPaused(v) { if (phase !== 'pitching' && phase !== 'flight') return; paused = v; stop(); update(); draw(); if (!paused) run(); }
    function draw() { if (!view) return; const { ctx: c, w, h } = view; c.clearRect(0, 0, w, h); const sky = c.createLinearGradient(0, 0, 0, h); sky.addColorStop(0, '#0e213e'); sky.addColorStop(1, '#183b42'); c.fillStyle = sky; c.fillRect(0, 0, w, h);
      // A small stadium, patterned grandstands and floodlights.
      for (let row = 0; row < 3; row++) for (let col = 0; col < 45; col++) { c.fillStyle = ['#3d6578', '#506776', '#d0b57c', '#6c93a3'][(col * 7 + row * 3) % 4]; c.fillRect(col * w / 44, h * (.12 + row * .038), Math.max(2, w / 90), Math.max(2, h / 60)); }
      c.strokeStyle = '#638899'; c.lineWidth = 3; c.beginPath(); c.moveTo(0, h * .27); c.lineTo(w, h * .27); c.stroke();
      [w * .09, w * .91].forEach(x => { c.strokeStyle = '#607782'; c.lineWidth = 5; c.beginPath(); c.moveTo(x, h * .02); c.lineTo(x, h * .24); c.stroke(); for (let n = -1; n <= 1; n++) roundRect(c, x + n * 12 - 4, h * .035, 8, 10, 2, '#fff5bb'); });
      path(c, [[0, h * .30], [w, h * .30], [w, h], [0, h]], '#256447');
      for (let n = 0; n < 8; n++) path(c, [[w * (.5 - n * .09), h * .30], [w * (.5 - (n + .5) * .09), h * .30], [w * (.5 - (n + .5) * .23), h], [w * (.5 - n * .23), h]], '#2b7050');
      const home = [w * .50, h * .87], first = [w * .71, h * .66], second = [w * .50, h * .44], third = [w * .29, h * .66]; path(c, [home, first, second, third], '#bb915d'); path(c, [[w * .5, h * .80], [w * .64, h * .66], [w * .5, h * .51], [w * .36, h * .66]], '#377755');
      c.strokeStyle = '#e4e8bd'; c.lineWidth = 2; c.beginPath(); c.moveTo(0, h * .37); c.lineTo(home[0], home[1]); c.lineTo(w, h * .37); c.stroke();
      [first, second, third].forEach((p, i) => { c.save(); c.translate(p[0], p[1]); c.rotate(Math.PI / 4); c.fillStyle = '#fcf6da'; c.fillRect(-5, -5, 10, 10); c.restore(); if (bases[i]) { circle(c, p[0], p[1] - 14, Math.max(5, w / 110), '#ffdd7b', '#493b1b'); c.fillStyle = '#273626'; c.font = 'bold 9px sans-serif'; c.textAlign = 'center'; c.fillText('M', p[0], p[1] - 11); } });
      path(c, [[home[0] - 7, home[1] - 4], [home[0] + 7, home[1] - 4], [home[0] + 7, home[1] + 3], [home[0], home[1] + 9], [home[0] - 7, home[1] + 3]], '#fffbe9');
      // Pitcher and batter are drawn as simple small ballplayers.
      circle(c, w * .5, h * .56, h * .025, '#bc9871'); roundRect(c, w * .49, h * .50, w * .02, h * .054, 3, '#a8d3c9'); circle(c, w * .5, h * .48, h * .018, '#e3bc95');
      const bx = w * .45, by = h * .86; roundRect(c, bx - w * .01, by - h * .045, w * .025, h * .055, 3, '#9ff2d1'); circle(c, bx, by - h * .068, h * .022, '#f2c992'); roundRect(c, bx - h * .025, by - h * .096, h * .05, h * .018, 4, '#1c4256'); c.strokeStyle = '#e3b965'; c.lineWidth = Math.max(4, w * .007); c.lineCap = 'round'; c.beginPath(); c.moveTo(bx + 7, by - h * .024); const swinging = swingStamp && performance.now() - swingStamp < 450; c.lineTo(bx + (swinging ? w * .11 : -w * .018), by - (swinging ? h * .06 : h * .145)); c.stroke();
      if (phase === 'pitching' || phase === 'flight') { let x, y, r; if (phase === 'flight') { const t = flightElapsed / 900; x = w * (.51 + .22 * t); y = h * (.79 - .8 * t + .24 * t * t); r = (1 - t * .65) * h * .022; } else { const t = clamp(pitchT, 0, 1.15); x = w * .505; y = h * (.54 + .32 * t); r = h * (.006 + .020 * t * t); } circle(c, x + 3, y + 5, r, '#173b37'); circle(c, x, y, r, '#fff9e9'); if (r > 4) { c.strokeStyle = '#c34a43'; c.lineWidth = 1; c.beginPath(); c.arc(x - r * .45, y, r * .6, -.8, .8); c.stroke(); } }
      c.textAlign = 'center'; c.font = '800 ' + Math.max(13, w * .025) + 'px sans-serif'; c.fillStyle = '#ecdeb0'; c.fillText('MAX’S BALLPARK', w * .5, h * .08);
      if (paused || phase === 'gameover') { c.fillStyle = 'rgba(5,19,30,.72)'; c.fillRect(0, 0, w, h); c.fillStyle = '#f7edcf'; c.font = '800 ' + Math.max(24, w * .06) + 'px sans-serif'; c.fillText(paused ? 'PAUSED' : 'NICE GAME, MAX!', w / 2, h * .45); c.font = '600 ' + Math.max(15, w * .03) + 'px sans-serif'; c.fillStyle = '#9af0d0'; c.fillText(paused ? 'Tap Resume when you’re ready.' : score + (score === 1 ? ' RUN' : ' RUNS'), w / 2, h * .57); }
    }
    view = setupCanvas(s, canvas, 1.68, draw); view.resize();
    s.on(practice, 'click', () => reset('practice')); s.on(regular, 'click', () => reset('game')); s.on(pitch, 'click', startPitch); s.on(swing, 'click', swingBat); s.on(pause, 'click', () => setPaused(!paused)); s.on(canvas, 'pointerdown', e => { e.preventDefault(); if (phase === 'pitching') swingBat(); }); s.on(read, 'click', () => s.api.read('Tap Pitch. Watch the ball and the white dot. When the dot reaches the bright gold zone, tap Swing. A hit moves your runners. Try to bring them home.'));
    s.on(document, 'keydown', e => { if (e.target.matches('input,textarea,select') || e.altKey || e.ctrlKey || e.metaKey || e.repeat) return; if (e.code === 'Space' && e.target.tagName !== 'BUTTON') { e.preventDefault(); phase === 'pitching' ? swingBat() : startPitch(); } else if (e.key.toLowerCase() === 'p') { e.preventDefault(); setPaused(!paused); } });
    s.on(document, 'visibilitychange', () => { if (document.hidden && (phase === 'pitching' || phase === 'flight')) setPaused(true); }); s.clean.push(stop); reset();
  }

  // POCKET BLOCKS: a slow, original falling-block puzzle with explicit controls.
  function blocks(s) {
    s.root.classList.add('game-blocks');
    intro(s, 'Shapes + planning', 'Pocket Blocks', 'Move and turn the falling shape. Fill a whole row with no gaps to clear it. Take your time—there’s no speed-up.');
    const layout = el('div', 'game-block-layout'), stage = el('div', 'game-stage'), canvas = el('canvas', 'game-canvas game-block-canvas'); canvas.setAttribute('aria-label', 'Falling-block board. Use the large arrow, turn, and drop buttons.'); canvas.setAttribute('role', 'img'); stage.append(canvas); const panel = el('div', 'game-block-panel'); layout.append(stage, panel); s.root.append(layout);
    const stats = el('div', 'game-stats'), rowsStat = stat('Rows', 0), bestStat = stat('Best rows', Number(s.api.get('blocks-best', 0)) || 0); stats.append(rowsStat.outer, bestStat.outer); panel.append(stats);
    const nextBox = el('div', 'game-next'), nextLabel = el('span', 'game-small', 'NEXT'), nextShape = el('div', 'game-mini-shape'); nextShape.setAttribute('aria-hidden', 'true'); nextBox.append(nextLabel, nextShape); panel.append(nextBox);
    const controls = el('div', 'game-block-controls'), left = button('←'), rotate = button('↻'), right = button('→'), drop = button('Drop ↓', 'game-primary game-drop'); left.setAttribute('aria-label', 'Move left'); right.setAttribute('aria-label', 'Move right'); rotate.setAttribute('aria-label', 'Turn shape clockwise'); controls.append(left, rotate, right, drop); panel.append(controls);
    const pause = button('Start', 'game-gold'), restart = button('New board', 'game-muted-button'); panel.append(pause, restart);
    const fb = feedback(); fb.title.textContent = 'Build a complete row.'; fb.text.textContent = 'The dotted shape shows where your block will land.'; panel.append(fb.root);
    const tip = el('div', 'game-callout'); tip.append(el('p', '', 'Try turning a shape before dropping it. You can fit it into a different space.')); panel.append(tip); s.root.append(el('p', 'game-keyboard-hint', 'Keyboard: ← → move · ↑ turn · ↓ lower · Space drop · P pause'));
    s.root.append(el('p', 'game-footer-note', 'Puzzle connection: Alexey Pajitnov created Tetris in Moscow in 1984. Pocket Blocks is our own small falling-block puzzle, inspired by fitting shapes together.'));
    const COLS = 10, ROWS = 18, SHAPES = [ [[1,1,1,1]], [[1,1],[1,1]], [[0,1,0],[1,1,1]], [[0,1,1],[1,1,0]], [[1,1,0],[0,1,1]], [[1,0,0],[1,1,1]], [[0,0,1],[1,1,1]] ], COLORS = ['#76d6e3','#ffda7b','#bfa4ed','#91e8be','#efb295','#a9c6fc','#e3a2cb'];
    let board = [], active = null, next = null, bag = [], rows = 0, best = Number(s.api.get('blocks-best', 0)) || 0, state = 'idle', elapsed = 0, last = null, raf = 0, view;
    function freshPiece() { if (!bag.length) bag = shuffle([0,1,2,3,4,5,6]); const i = bag.pop(); return { matrix: SHAPES[i].map(r => r.slice()), color: COLORS[i], x: 3, y: 0 }; }
    function fits(piece, dx, dy, matrix) { const m = matrix || piece.matrix; for (let y = 0; y < m.length; y++) for (let x = 0; x < m[y].length; x++) if (m[y][x]) { const xx = piece.x + x + dx, yy = piece.y + y + dy; if (xx < 0 || xx >= COLS || yy >= ROWS || (yy >= 0 && board[yy][xx])) return false; } return true; }
    function displayNext() { nextShape.replaceChildren(); nextShape.style.gridTemplateColumns = 'repeat(' + next.matrix[0].length + ',17px)'; next.matrix.forEach(row => row.forEach(value => { const cell = el('span', 'game-mini-cell'); cell.style.backgroundColor = value ? next.color : 'transparent'; nextShape.append(cell); })); }
    function update() { rowsStat.number.textContent = rows; bestStat.number.textContent = best; pause.textContent = state === 'playing' ? 'Pause' : state === 'over' ? 'Play again' : state === 'idle' ? 'Start' : 'Resume'; [left, right, rotate, drop].forEach(b => b.disabled = state !== 'playing'); }
    function stop() { if (raf) cancelAnimationFrame(raf); raf = 0; last = null; }
    function run() { if (!raf && state === 'playing' && !document.hidden) raf = requestAnimationFrame(frame); }
    function spawn() { active = next; active.x = Math.floor((COLS - active.matrix[0].length) / 2); active.y = 0; next = freshPiece(); displayNext(); if (!fits(active, 0, 0)) { state = 'over'; stop(); fb.title.textContent = 'Your board is full.'; fb.text.textContent = rows + (rows === 1 ? ' row cleared. ' : ' rows cleared. ') + 'Try a fresh board and look for empty spaces.'; if (rows > 0) s.api.award('blocks-builder', 'Shape builder'); } update(); }
    function lock() { active.matrix.forEach((row, y) => row.forEach((value, x) => { if (value && active.y + y >= 0) board[active.y + y][active.x + x] = active.color; })); const remaining = board.filter(row => row.some(cell => !cell)); const cleared = ROWS - remaining.length; while (remaining.length < ROWS) remaining.unshift(Array(COLS).fill(null)); board = remaining; if (cleared) { rows += cleared; if (rows > best) { best = rows; s.api.set('blocks-best', best); } fb.title.textContent = cleared === 1 ? 'One whole row!' : cleared + ' rows at once!'; fb.text.textContent = 'You filled every space. Now there is room to build again.'; s.api.award('blocks-first-row', 'Shape builder'); } elapsed = 0; spawn(); }
    function step() { if (state !== 'playing') return; if (fits(active, 0, 1)) active.y++; else lock(); draw(); }
    function move(dx) { if (state === 'playing' && fits(active, dx, 0)) { active.x += dx; draw(); } }
    function turn() { if (state !== 'playing') return; const m = active.matrix[0].map((_, x) => active.matrix.map(row => row[x]).reverse()); for (const dx of [0, -1, 1, -2, 2]) if (fits(active, dx, 0, m)) { active.x += dx; active.matrix = m; draw(); return; } }
    function hardDrop() { if (state !== 'playing') return; while (fits(active, 0, 1)) active.y++; lock(); draw(); }
    function reset() { stop(); board = Array.from({length: ROWS}, () => Array(COLS).fill(null)); bag = []; rows = elapsed = 0; next = freshPiece(); state = 'idle'; spawn(); fb.title.textContent = 'Build a complete row.'; fb.text.textContent = 'Tap Start when you’re ready. The dotted shape is your landing guide.'; update(); draw(); }
    function toggle() { if (state === 'over') reset(); state = state === 'playing' ? 'paused' : 'playing'; stop(); update(); draw(); run(); }
    function frame(time) { raf = 0; if (state !== 'playing' || !s.alive() || document.hidden) return; const dt = last == null ? 0 : Math.min(time - last, 100); last = time; elapsed += dt; if (elapsed >= 1050) { elapsed = 0; step(); } run(); }
    function drawCell(c, x, y, color, ghost) { const size = view.w / COLS, cellH = view.h / ROWS, pad = Math.max(1, size * .06); if (ghost) { c.strokeStyle = color; c.lineWidth = 2; c.setLineDash([3, 3]); c.strokeRect(x * size + pad + 1, y * cellH + pad + 1, size - pad * 2 - 2, cellH - pad * 2 - 2); c.setLineDash([]); } else { roundRect(c, x * size + pad, y * cellH + pad, size - pad * 2, cellH - pad * 2, 4, color); c.fillStyle = 'rgba(255,255,255,.24)'; c.fillRect(x * size + pad + 3, y * cellH + pad + 3, Math.max(1, size - pad * 2 - 6), 3); } }
    function draw() { if (!view || !board.length) return; const {ctx:c,w,h} = view; c.clearRect(0,0,w,h); c.fillStyle = '#091b2c'; c.fillRect(0,0,w,h); c.strokeStyle = '#142f43'; c.lineWidth = 1; for (let x=0;x<=COLS;x++) { c.beginPath(); c.moveTo(x*w/COLS,0); c.lineTo(x*w/COLS,h); c.stroke(); } for (let y=0;y<=ROWS;y++) { c.beginPath(); c.moveTo(0,y*h/ROWS); c.lineTo(w,y*h/ROWS); c.stroke(); } board.forEach((row,y) => row.forEach((color,x) => { if(color) drawCell(c,x,y,color,false); })); if (active) { let dy=0; while(fits(active,0,dy+1)) dy++; active.matrix.forEach((row,y) => row.forEach((v,x) => { if(v) drawCell(c,active.x+x,active.y+y+dy,active.color,true); })); active.matrix.forEach((row,y) => row.forEach((v,x) => { if(v) drawCell(c,active.x+x,active.y+y,active.color,false); })); } if(state!=='playing') { c.fillStyle='rgba(4,15,25,.74)'; c.fillRect(0,0,w,h); c.fillStyle='#f8efda'; c.font='800 '+Math.max(18,w*.09)+'px sans-serif'; c.textAlign='center'; c.fillText(state==='idle'?'READY TO BUILD?':state==='over'?'NICE BUILDING!':'PAUSED',w/2,h*.45); c.font='500 '+Math.max(12,w*.046)+'px sans-serif'; c.fillStyle='#9eeed3'; c.fillText(state==='over'?'Try a fresh board.':state==='idle'?'Tap Start to begin.':'Tap Resume to keep going.',w/2,h*.52); } }
    view = setupCanvas(s,canvas,10/18,draw); view.resize(); s.on(left,'click',()=>move(-1)); s.on(right,'click',()=>move(1)); s.on(rotate,'click',turn); s.on(drop,'click',hardDrop); s.on(pause,'click',toggle); s.on(restart,'click',reset);
    s.on(document,'keydown',e=> { if(e.target.matches('input,textarea,select') || e.altKey || e.ctrlKey || e.metaKey) return; const action = {ArrowLeft:()=>move(-1),ArrowRight:()=>move(1),ArrowUp:turn,ArrowDown:step}; if(action[e.code]) {e.preventDefault();action[e.code]();} else if(e.code==='Space' && e.target.tagName!=='BUTTON') {e.preventDefault();state==='playing'?hardDrop():toggle();} else if(e.key.toLowerCase()==='p'&&!e.repeat){e.preventDefault();toggle();} }); s.on(document,'visibilitychange',()=>{if(document.hidden&&state==='playing'){state='paused';stop();update();draw();}}); s.clean.push(stop); reset();
  }

  // PATTERN STUDIO: an eight-by-eight canvas made from real, keyboard-friendly buttons.
  function patterns(s) {
    intro(s, 'Art + symmetry', 'Pattern Studio', 'Pick a color. Tap or slide across the squares. Turn on Mirror to make both sides match!');
    const SIZE = 8, colors = ['#112738', '#f5f0d8', '#ffd97b', '#ef987f', '#bda2ed', '#78ccea', '#91e8be', '#44775e'];
    const names = ['Midnight', 'Cream', 'Sunshine', 'Coral', 'Lavender', 'Ocean', 'Mint', 'Forest'];
    const saved = s.api.get('pattern-picture', null);
    let cells = Array.isArray(saved) && saved.length === SIZE * SIZE && saved.every(c => Number.isInteger(c) && c >= 0 && c < colors.length) ? saved.slice() : Array(SIZE * SIZE).fill(0);
    let chosen = 2, mirror = false, painting = false, pointerId = null, undoStack = [], strokeBefore = null, focusIndex = 0;
    const layout = el('div', 'game-mosaic-layout'), board = el('div', 'game-mosaic-board'), side = el('div', 'game-mosaic-side');
    board.setAttribute('role', 'group'); board.setAttribute('aria-label', '8 by 8 drawing grid. Use arrow keys to move, then Space to color a square.');
    const palette = el('div', 'game-palette'); palette.setAttribute('role', 'group'); palette.setAttribute('aria-label', 'Choose a paint color');
    const swatches = colors.map((color, i) => { const b = button('', 'game-swatch'); b.className = 'game-swatch'; b.style.backgroundColor = color; b.setAttribute('aria-label', names[i] + (i === 0 ? ' / erase' : '')); b.setAttribute('title', names[i]); s.on(b, 'click', () => { chosen = i; updatePalette(); }); palette.append(b); return b; });
    const colorLabel = el('p', 'game-small'), mirrorButton = button('Mirror: off'), tools = el('div', 'game-mosaic-tools'), undo = button('Undo'), clear = button('Clear'), starter = button('Try a pattern'), save = button('Save my picture', 'game-primary'); tools.append(undo, clear, starter, save);
    const prompt = el('p', 'game-mosaic-question', 'Challenge: can you make a butterfly, a robot, or the letter M?');
    const fb = feedback(); fb.title.textContent = saved ? 'Your picture is back.' : 'Every great picture starts with one square.'; fb.text.textContent = saved ? 'Keep adding to it, or start a new design.' : '8 rows × 8 columns = 64 little squares.';
    side.append(palette, colorLabel, mirrorButton, tools, prompt, fb.root); layout.append(board, side); s.root.append(layout);
    s.root.append(el('p', 'game-footer-note', 'Symmetry means two sides match like a reflection. Save keeps one picture in this browser on this device. Undo can bring back your last changes.'));
    const pixels = cells.map((_, i) => { const b = button('', ''); b.className = 'game-pixel'; b.dataset.pixel = i; b.tabIndex = i === 0 ? 0 : -1; board.append(b); return b; });
    function updatePalette() { swatches.forEach((b, i) => b.setAttribute('aria-pressed', i === chosen)); colorLabel.textContent = 'Color: ' + names[chosen] + (chosen === 0 ? ' (eraser)' : ''); }
    function render() { pixels.forEach((b, i) => { b.style.backgroundColor = colors[cells[i]]; b.setAttribute('aria-label', 'Row ' + (Math.floor(i / SIZE) + 1) + ', column ' + (i % SIZE + 1) + ': ' + names[cells[i]]); }); undo.disabled = !undoStack.length; mirrorButton.setAttribute('aria-pressed', mirror); mirrorButton.textContent = mirror ? 'Mirror: on ↔' : 'Mirror: off'; board.classList.toggle('game-mirror-on', mirror); }
    function record(before) { if (before.some((c, i) => c !== cells[i])) { undoStack.push(before); if (undoStack.length > 25) undoStack.shift(); } render(); }
    function colorCell(index) { if (!Number.isInteger(index) || index < 0 || index >= cells.length) return; cells[index] = chosen; if (mirror) cells[Math.floor(index / SIZE) * SIZE + SIZE - 1 - index % SIZE] = chosen; render(); }
    function beginStroke(e) { const cell = e.target.closest('[data-pixel]'); if (!cell || e.button > 0 || painting) return; e.preventDefault(); painting = true; pointerId = e.pointerId; strokeBefore = cells.slice(); focusIndex = Number(cell.dataset.pixel); setFocus(focusIndex, false); colorCell(focusIndex); if (board.setPointerCapture) { try { board.setPointerCapture(pointerId); } catch (_) {} } }
    function moveStroke(e) { if (!painting || e.pointerId !== pointerId) return; e.preventDefault(); const box = board.getBoundingClientRect(), style = getComputedStyle(board), left = parseFloat(style.borderLeftWidth) || 0, top = parseFloat(style.borderTopWidth) || 0, width = box.width - left - (parseFloat(style.borderRightWidth) || 0), height = box.height - top - (parseFloat(style.borderBottomWidth) || 0); const x = e.clientX - box.left - left, y = e.clientY - box.top - top; if (x >= 0 && y >= 0 && x < width && y < height) colorCell(Math.floor(y / height * SIZE) * SIZE + Math.floor(x / width * SIZE)); }
    function endStroke(e) { if (!painting || (e && e.pointerId !== pointerId)) return; painting = false; if (board.releasePointerCapture) { try { board.releasePointerCapture(pointerId); } catch (_) {} } pointerId = null; record(strokeBefore); strokeBefore = null; }
    function setFocus(index, focus) { focusIndex = clamp(index, 0, 63); pixels.forEach((p, i) => p.tabIndex = i === focusIndex ? 0 : -1); if (focus) pixels[focusIndex].focus(); }
    s.on(board, 'pointerdown', beginStroke); s.on(board, 'pointermove', moveStroke); s.on(board, 'pointerup', endStroke); s.on(board, 'pointercancel', endStroke); s.on(board, 'lostpointercapture', endStroke);
    // A click with detail 0 comes from a keyboard or assistive technology, not a painted pointer stroke.
    s.on(board, 'click', e => { const cell = e.target.closest('[data-pixel]'); if (cell && e.detail === 0) { const before = cells.slice(); colorCell(Number(cell.dataset.pixel)); record(before); } });
    s.on(board, 'keydown', e => { const cell = e.target.closest('[data-pixel]'); if (!cell) return; const i = Number(cell.dataset.pixel); const offsets = {ArrowLeft: -1, ArrowRight: 1, ArrowUp: -SIZE, ArrowDown: SIZE}; if (offsets[e.key]) { e.preventDefault(); setFocus(i + offsets[e.key], true); } else if (e.key === 'Home') { e.preventDefault(); setFocus(0, true); } else if (e.key === 'End') { e.preventDefault(); setFocus(63, true); } });
    s.on(mirrorButton, 'click', () => { mirror = !mirror; render(); fb.title.textContent = mirror ? 'Two sides, one idea.' : 'Free drawing is on.'; fb.text.textContent = mirror ? 'Your next square will also appear on the other side. Old squares stay where they are.' : 'Each square can now be a different color.'; });
    s.on(undo, 'click', () => { if (undoStack.length) { cells = undoStack.pop(); render(); fb.title.textContent = 'One step back.'; fb.text.textContent = 'Your last change has been undone.'; } });
    s.on(clear, 'click', () => { const before = cells.slice(); cells.fill(0); record(before); fb.title.textContent = 'A fresh canvas.'; fb.text.textContent = 'Changed your mind? Tap Undo to bring your picture back.'; });
    s.on(starter, 'click', () => { const before = cells.slice(); cells = Array.from({length: 64}, (_, i) => { const row = Math.floor(i / SIZE), col = i % SIZE; return (Math.abs(3.5 - row) + Math.abs(3.5 - col)) % 3 < 1 ? 5 : (row + col) % 2 ? 6 : 0; }); record(before); fb.title.textContent = 'A pattern to play with.'; fb.text.textContent = 'What repeats? Change any square to make this picture your own.'; });
    s.on(save, 'click', () => { s.api.set('pattern-picture', cells.slice()); s.api.award('pattern-artist', 'Pattern artist'); fb.title.textContent = 'Picture saved in your lab.'; fb.text.textContent = 'It will be here when you come back in this browser. You can keep creating.'; });
    s.clean.push(() => { painting = false; strokeBefore = null; }); updatePalette(); render();
  }

  // OCEAN SIZE LAB: rounded examples, not a claim that every adult has one fixed size.
  const OCEAN_ANIMALS = [
    {id:'blue',name:'Blue whale',feet:100,color:'#84b6d3',kind:'whale',fact:'The biggest animal eats tiny, shrimp-like animals called krill. It strains them from seawater.',source:'https://www.fisheries.noaa.gov/species/blue-whale',sourceName:'NOAA: blue whale'},
    {id:'sperm',name:'Sperm whale',feet:52,color:'#98a4bf',kind:'sperm',fact:'This deep diver makes clicks and listens for echoes to find food in dark water.',source:'https://www.fisheries.noaa.gov/species/sperm-whale',sourceName:'NOAA: sperm whale'},
    {id:'whaleshark',name:'Whale shark',feet:40,color:'#71b0bd',kind:'shark',fact:'It is a fish, even though its name says whale! It filters tiny food from water.',source:'https://oceanservice.noaa.gov/facts/bigfish.html',sourceName:'NOAA: whale shark'},
    {id:'dolphin',name:'Bottlenose dolphin',feet:10,color:'#a1c4d9',kind:'dolphin',fact:'Dolphins make sounds and listen for echoes. The echoes help them find fish.',source:'https://www.fisheries.noaa.gov/species/common-bottlenose-dolphin',sourceName:'NOAA: bottlenose dolphin'},
    {id:'lemon',name:'Lemon shark',feet:8,color:'#c4bf80',kind:'shark',fact:'Its yellow-brown color helps it blend into sandy water. You met a lemon shark in Exuma, Max!',source:'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/lemon-shark/',sourceName:'Florida Museum: lemon shark'},
    {id:'turtle',name:'Green sea turtle',feet:3,color:'#9bc78c',kind:'turtle',fact:'Grown-up green turtles mostly eat seagrass and algae. They come to the surface to breathe air.',source:'https://www.fisheries.noaa.gov/species/green-turtle',sourceName:'NOAA: green turtle'}
  ];
  function animalIcon(animal) {
    const NS = 'http://www.w3.org/2000/svg', svg = document.createElementNS(NS, 'svg'); svg.setAttribute('viewBox','0 0 240 100'); svg.setAttribute('class','game-animal-icon'); svg.setAttribute('aria-hidden','true');
    function shape(tag, attrs) { const n = document.createElementNS(NS, tag); Object.keys(attrs).forEach(k => n.setAttribute(k, attrs[k])); svg.append(n); return n; }
    const color = animal.color;
    if (animal.kind === 'turtle') { shape('path',{d:'M83 32 Q35 2 50 30 L82 52 M80 66 Q49 98 74 87 L103 71 M151 35 Q194 5 176 31 L155 51 M151 65 Q183 93 166 85 L139 72',fill:color}); shape('ellipse',{cx:118,cy:53,rx:49,ry:29,fill:'#42745c',stroke:color,'stroke-width':4}); shape('ellipse',{cx:182,cy:53,rx:22,ry:12,fill:color}); shape('path',{d:'M73 52 L58 59 L76 60 M105 28 L118 53 L102 78 M137 29 L118 53 L137 78 M78 52 L162 52',fill:'none',stroke:color,'stroke-width':2}); shape('circle',{cx:191,cy:49,r:2.5,fill:'#102738'}); }
    else {
      const head = animal.kind === 'sperm' ? 'M174 31 Q215 24 216 39 L215 62 Q185 79 132 70 Q92 66 61 57 L30 77 L39 53 L24 34 L61 47 Q115 23 174 31Z' : animal.kind === 'dolphin' ? 'M51 47 Q102 25 156 39 Q178 38 190 49 L219 53 L211 59 L179 57 Q139 81 91 60 L48 60 L23 78 L34 53 L19 35Z' : animal.kind === 'shark' ? 'M58 44 Q110 31 170 40 L217 52 Q183 76 125 63 L64 57 L26 81 L39 52 L21 23Z' : 'M58 47 Q107 26 167 35 Q209 36 218 52 Q211 76 150 72 Q97 70 57 58 L31 77 L37 53 L24 33Z';
      shape('path',{d:head,fill:color});
      shape('path',{d:animal.kind==='shark'?'M109 40 L130 14 L146 43 M116 62 L149 90 L143 62':animal.kind==='dolphin'?'M107 40 Q119 17 135 42 M135 64 Q139 89 159 68':'M128 67 Q120 91 155 73',fill:color});
      if(animal.kind==='whale') shape('path',{d:'M89 54 Q146 76 207 57',fill:'none',stroke:'#d5ebef','stroke-width':2,opacity:.7});
      if(animal.kind==='sperm') shape('path',{d:'M166 65 L211 58',fill:'none',stroke:'#dbe1e8','stroke-width':2});
      if(animal.kind==='shark') [166,172,178].forEach(x=>shape('path',{d:'M'+x+' 47 l-3 12',stroke:'#2d5c67','stroke-width':2}));
      if(animal.id==='whaleshark') for(let i=0;i<19;i++) shape('circle',{cx:75+(i%7)*16,cy:44+Math.floor(i/7)*7,r:1.7,fill:'#e2ecd5'});
      shape('circle',{cx:animal.kind==='sperm'?198:196,cy:48,r:2.4,fill:'#0b2132'});
    }
    return svg;
  }
  function ocean(s) {
    intro(s, 'Ocean life + comparing numbers', 'Ocean Size Lab', 'Meet six ocean animals. Compare their lengths, then tap the longer example. There’s no timer.');
    const sizeNote = el('p', 'game-small', 'These are rounded examples of grown-up animals. Real animals come in different sizes. Drawings are not to scale; the comparison bars are.'); s.root.append(sizeNote);
    const top = el('div','game-action-row'), progress = el('div','game-ocean-progress'), progressText = el('span','game-small'), hear = button('Read this round', 'game-muted-button'); top.append(progress, progressText, hear); s.root.append(top);
    const roundTitle = el('h3','game-ocean-question'), choices = el('div','game-ocean-choices'), comparison = el('div','game-ocean-comparison'), fb = feedback(), next = button('Next ocean pair →','game-primary');
    s.root.append(roundTitle, choices, comparison, fb.root, next);
    const collectionTitle = el('h3','game-collection-title','Meet the whole crew'), collection = el('div','game-ocean-collection'); s.root.append(collectionTitle, collection);
    const sourceBox = el('details','game-source-links'), sourceSummary = el('summary','','Animal fact sources'), list = el('ul'); OCEAN_ANIMALS.forEach(a=>{const li=el('li'),link=el('a','',a.sourceName);link.href=a.source;link.target='_blank';link.rel='noopener noreferrer';li.append(link);list.append(li);}); sourceBox.append(sourceSummary,list);s.root.append(sourceBox);
    let rounds = [], round = 0, answered = false, buttons = [], dots = [], shownFact = '';
    function reset() { rounds = shuffle([[0,5],[1,4],[2,3],[5,3],[2,4],[0,1]]).map(p=>shuffle(p)); round=0; progress.replaceChildren(); dots=rounds.map((_,i)=>{const dot=el('span','game-progress-dot');dot.setAttribute('aria-hidden','true');progress.append(dot);return dot;}); showRound(); }
    function lengthLabel(a) { return a.feet + ' feet'; }
    function showRound() { answered=false; const pair=rounds[round].map(i=>OCEAN_ANIMALS[i]); roundTitle.textContent='Which example is longer?';progressText.textContent='Pair '+(round+1)+' of '+rounds.length;choices.replaceChildren();comparison.replaceChildren();comparison.hidden=true;next.hidden=true;next.textContent=round===rounds.length-1?'Finish this dive →':'Next ocean pair →';fb.title.textContent='Look at the lengths.';fb.text.textContent='A larger number means a longer animal in this comparison.';shownFact='';buttons=pair.map(a=>{const b=button('','game-animal-choice');b.append(animalIcon(a),el('strong','game-animal-name',a.name),el('span','game-animal-size',lengthLabel(a)));b.setAttribute('aria-label',a.name+', '+lengthLabel(a));s.on(b,'click',()=>choose(a,pair,b));choices.append(b);return b;}); }
    function choose(animal,pair,b) { if(answered)return; const winner=pair[0].feet>pair[1].feet?pair[0]:pair[1]; if(animal!==winner){b.classList.add('game-wrong');b.setAttribute('aria-label',animal.name+', '+lengthLabel(animal)+'. Try the other animal.');fb.title.textContent='Compare the numbers once more.';fb.text.textContent=pair[0].feet+' feet and '+pair[1].feet+' feet—which number is larger?';return;} answered=true;b.classList.remove('game-wrong');b.classList.add('game-correct');buttons.forEach(x=>x.disabled=true);dots[round].classList.add('game-done');comparison.hidden=false;const biggest=Math.max(...pair.map(a=>a.feet));pair.forEach(a=>{const row=el('div','game-length-row'),label=el('div','game-length-label'),track=el('div','game-length-track'),bar=el('div','game-length-bar');label.append(el('strong','',a.name),el('span','',lengthLabel(a)));bar.style.width=(a.feet/biggest*100)+'%';bar.style.backgroundColor=a.color;track.append(bar);row.append(label,track);comparison.append(row);});fb.title.textContent=winner.name+' is longer in our example.';shownFact=winner.fact;fb.text.textContent=winner.fact;next.hidden=false; }
    function finish() { choices.replaceChildren();comparison.hidden=true;roundTitle.textContent='Six pairs explored. Nice dive, Max!';progressText.textContent='6 of 6 explored';fb.title.textContent='Small or enormous, each animal has a story.';fb.text.textContent='Tap any animal below to learn its special fact, or dive again with a shuffled set of pairs.';next.textContent='Dive again';s.api.award('ocean-explorer','Ocean explorer'); }
    s.on(next,'click',()=>{if(round>=rounds.length){reset();return;}round++;if(round>=rounds.length)finish();else showRound();});
    OCEAN_ANIMALS.forEach(a=>{const card=button('','game-ocean-card');card.append(animalIcon(a),el('strong','',a.name),el('span','',lengthLabel(a)+' example'));s.on(card,'click',()=>{fb.title.textContent=a.name;fb.text.textContent=a.fact;shownFact=a.fact;});collection.append(card);});
    s.on(hear,'click',()=>{if(shownFact)s.api.read(shownFact);else if(round<rounds.length){const pair=rounds[round].map(i=>OCEAN_ANIMALS[i]);s.api.read('Which example is longer? '+pair.map(a=>a.name+', '+lengthLabel(a)).join('. ')+'.');}else s.api.read('You explored all six pairs. Tap an animal to learn its special fact.');}); reset();
  }

  const modules = { baseball, blocks, patterns, ocean };
  window.MLL_GAMES = {
    mount(kind, container, api) {
      if (!container || typeof container.appendChild !== 'function') throw new TypeError('A game needs a container element.');
      const s = createScope(container, api);
      if (!modules[kind]) { s.root.append(el('p','game-help','This game is not available yet. Choose another adventure.')); return () => s.dispose(); }
      try { modules[kind](s); } catch (error) { s.dispose(); throw error; }
      return () => s.dispose();
    }
  };
}());
