/* Max's Learning Lab — edit content in data/, not in this application shell. */
(function () {
  'use strict';
  const config = window.MLL_CONFIG;
  const family = (window.MLL_PLACES_FAMILY || []).map(p => ({...p, family:true}));
  const surprises = [...(window.MLL_PLACES_A || []), ...(window.MLL_PLACES_B || [])];
  const places = [...family, ...surprises];
  const people = window.MLL_PEOPLE || [], photos = window.MLL_PHOTOS || {};
  const byId = new Map(places.map(p => [p.id,p]));
  const view = document.getElementById('view');
  const STORAGE = 'max-learning-lab-v1';
  const empty = () => ({version:1,name:config.name,badge:config.badges[0],visited:[],stamps:[],quiz:[],badges:{},deck:[],lastSurprise:null,games:{}});
  let memoryOnly=false;
  function normalize(input) {
    const next=empty();if(!input||typeof input!=='object')return next;
    if(typeof input.name==='string' && input.name.trim()) next.name=input.name.trim().slice(0,20);
    if(config.badges.includes(input.badge))next.badge=input.badge;
    for(const key of ['visited','stamps','deck'])if(Array.isArray(input[key]))next[key]=[...new Set(input[key].filter(id=>byId.has(id)))];
    if(Array.isArray(input.quiz))next.quiz=[...new Set(input.quiz.filter(id=>typeof id==='string'&&id.length<70))];
    if(input.badges&&typeof input.badges==='object')for(const[k,v]of Object.entries(input.badges))if(typeof v==='string'&&k.length<60)next.badges[k]=v.slice(0,90);
    if(input.games&&typeof input.games==='object'&&!Array.isArray(input.games))next.games=input.games;
    next.deck=next.deck.filter(id=>surprises.some(p=>p.id===id));
    if(byId.has(input.lastSurprise))next.lastSurprise=input.lastSurprise;
    return next;
  }
  let state;try{state=normalize(JSON.parse(localStorage.getItem(STORAGE)));}catch(e){state=empty();memoryOnly=true;}
  let dispose=null,toastTimer,readingButton=null,routeToken=0;
  const $=id=>document.getElementById(id);
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch(e){if(!memoryOnly)toast('Progress can’t be saved in this browser.');memoryOnly=true;}updateHeader();}
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
  function button(text,cls,fn){const b=el('button',cls||'button',text);b.type='button';if(fn)b.addEventListener('click',fn);return b;}
  function link(text,href,cls){const a=el('a',cls||'',text);a.href=href;return a;}
  function external(text,url,cls){const a=link(text,url,cls);a.target='_blank';a.rel='noopener noreferrer';return a;}
  function heading(kicker,title,description){const row=el('div','page-heading'),text=el('div');text.append(el('p','eyebrow',kicker),el('h1','',title));if(description)text.append(el('p','',description));row.append(text);return row;}
  function topNav(back='#home',label='← Explore the lab'){const n=el('nav','page-nav');n.setAttribute('aria-label','Activity navigation');n.append(link(label,back,'back-link'));if(back!=='#home')n.append(link('⌂ Home','#home','button small ghost'));view.append(n);return n;}
  function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('show');toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300);}
  function updateHeader(){ $('brand-name').textContent=state.name.toUpperCase()+"'S";$('avatar-symbol').textContent=state.badge;$('nav-count').textContent=state.visited.length; }
  function stopReading(){if('speechSynthesis'in window)window.speechSynthesis.cancel();if(readingButton){readingButton.classList.remove('listen-on');readingButton.textContent='◖ Listen';readingButton=null;}}
  function read(text,b){if(!('speechSynthesis'in window)){toast('Read-aloud is not available in this browser.');return;}if(b&&readingButton===b){stopReading();return;}stopReading();const u=new SpeechSynthesisUtterance(text);u.rate=.88;u.pitch=1;u.lang='en-US';const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='en-US'&&v.localService);if(voice)u.voice=voice;if(b){readingButton=b;b.textContent='■ Stop reading';b.classList.add('listen-on');}u.onend=u.onerror=()=>{if(readingButton===b&&b){b.textContent='◖ Listen';b.classList.remove('listen-on');readingButton=null;}};window.speechSynthesis.speak(u);}
  function award(key,label){if(state.badges[key])return;state.badges[key]=label;save();toast('✦ '+label);}
  function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
  function surprise(){if(!surprises.length)return;if(!state.deck.length){state.deck=shuffle(surprises.map(p=>p.id));if(state.deck.length>1&&state.deck[state.deck.length-1]===state.lastSurprise)[state.deck[0],state.deck[state.deck.length-1]]=[state.deck[state.deck.length-1],state.deck[0]];}const id=state.deck.pop();state.lastSurprise=id;save();location.hash='place/'+id+'?from=surprise';}
  function markVisited(id){if(!state.visited.includes(id)){state.visited.push(id);save();if(state.visited.length===5)award('five-places','Five-place explorer');if(state.visited.length===20)award('twenty-places','World wanderer');if(state.visited.length===places.length)award('all-places','Every destination discovered');}}
  function picture(p,cls,lazy=true){const photo=photos[p.id];const img=el('img',cls);img.alt=photo?.alt||p.photoAlt||p.name;if(photo?.src)img.src=photo.src;img.loading=lazy?'lazy':'eager';img.decoding='async';if(photo){img.width=photo.width||1000;img.height=photo.height||700;}return img;}
  function placeCard(p,from='places'){const a=link('', '#place/'+p.id+'?from='+from,'place-card');a.append(picture(p));a.append(el('span','place-tag',p.family?'FAMILY & FAVORITES':p.country));if(state.visited.includes(p.id))a.append(el('span','visited-dot','✓'));const c=el('div','place-card-copy');c.append(el('h2','',p.name),el('p','',p.hook));a.append(c);return a;}
  function surpriseCard(){const b=button('','place-card surprise-card',surprise);b.append(el('span','tiny-label',surprises.length+' PLACES • A NEW ONE EACH TIME'),el('span','surprise-symbol','✦'));const c=el('div','place-card-copy');c.append(el('h2','','Surprise me!'),el('p','','Ice caves? Dragons? A giant salt mirror? Let’s find out.'));b.append(c);return b;}
  function home(){
    document.title=state.name+"'s Learning Lab";
    const hero=el('section','home-hero'),copy=el('div','hero-copy');copy.append(el('p','eyebrow','YOUR CURIOSITY. YOUR ADVENTURE.'));const title=el('h1');title.append(document.createTextNode('Big world. '),el('br'),el('em','','Curious '+state.name+'.'));copy.append(title,el('p','lede',config.homeNote));const actions=el('div','hero-actions');actions.append(button('✦ Surprise me','button primary',surprise),link('Explore the map ↗','#map','button ghost'));copy.append(actions);hero.append(copy);
    const exuma=family.find(p=>p.id==='exuma')||family[2];const photo=link('','#place/'+exuma.id+'?from=home','hero-photo');photo.append(picture(exuma,'',false));const sticker=el('span','hero-sticker');sticker.append(el('strong','',String(places.length)),el('span','','PLACES TO GO'));photo.append(sticker);const hc=el('div','hero-photo-copy');hc.append(el('span','hero-label','A PLACE IN YOUR STORY'),el('h2','','Remember Exuma?'),el('p','','Blue water, fishing days, and the lemon shark you caught.'));photo.append(hc);hero.append(photo);view.append(hero);
    const section=el('div','section-title');section.append(el('h2','','Choose your adventure'),el('p','','Explore. Play. Make.'));view.append(section);const grid=el('div','module-grid');config.modules.forEach(m=>{const a=link('','#'+m.id,'module-card');a.style.setProperty('--tile-color',m.color);const symbol=el('span','module-symbol',m.icon);symbol.setAttribute('aria-hidden','true');if(m.id==='baseball'){symbol.textContent='';const ball=el('img');ball.src='assets/ui/baseball.svg';ball.alt='';ball.width=34;ball.height=34;symbol.append(ball);}a.append(symbol,el('p','eyebrow',m.tag),el('h3','',m.name),el('p','',m.hook),el('span','module-arrow','↗'));grid.append(a);});view.append(grid);
    const strip=el('section','passport-strip'),t=el('div');t.append(el('h3','',state.visited.length?state.visited.length+' places discovered. So much more to find.':'Your passport is ready.'),el('p','','Every place you open becomes part of your story.'));strip.append(t,link('My passport →','#passport','button small ghost'));view.append(strip);
  }
  function placeMenu(){topNav();view.append(heading('PLACES & PEOPLE','Where shall we go?','Start with a family place, or take a leap into somewhere new.'));const grid=el('div','place-grid');family.forEach(p=>grid.append(placeCard(p)));grid.append(surpriseCard());view.append(grid);const strip=el('div','passport-strip');strip.append(el('p','','Want to choose a place yourself? All '+places.length+' are waiting on the map.'),link('Open world map ↗','#map','button small'));view.append(strip);}
  function addCredit(p,container){const photo=photos[p.id];if(!photo)return;const c=el('p','photo-credit');c.append(document.createTextNode('Photo: '+photo.credit+' · '),external(photo.license,photo.licenseUrl||photo.source));container.append(c);}
  function sources(p){const d=el('details','fact-sources');d.append(el('summary','','Where these facts come from'));(p.sources||[]).forEach(s=>d.append(external(s.title,s.url)));return d;}
  function quiz(p){const q=el('section','quiz-card');q.append(el('p','eyebrow','YOUR TURN'),el('h2','',p.quiz.question));const opts=el('div','quiz-options'),feedback=el('p','quiz-feedback');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');p.quiz.options.forEach((text,i)=>{const b=button(text,'',()=>{if(i===p.quiz.answer){b.classList.add('correct');feedback.textContent='Yes! '+p.quiz.explain;[...opts.children].forEach(n=>n.disabled=true);b.disabled=false;if(!state.quiz.includes(p.id)){state.quiz.push(p.id);save();if(state.quiz.length===5)award('curious-five','Five curious answers');}}else{b.classList.add('retry');feedback.textContent='Try another idea. Look at the clues above.';}});opts.append(b);});q.append(opts,feedback);return q;}
  function stretch(p){const d=el('details','stretch');d.append(el('summary','','Think a little bigger: '+p.stretch.question),el('p','',p.stretch.answer));return d;}
  function profile(p,from){
    markVisited(p.id);document.title=p.name+' · '+state.name+"'s Lab";const back=from==='map'?'#map':from==='passport'?'#passport':from==='home'?'#home':'#places';topNav(back,from==='map'?'← Back to the map':from==='passport'?'← My passport':from==='home'?'← Explore the lab':'← All places');
    const grid=el('div','profile-layout'),visual=el('div'),image=el('div','profile-photo');if(photos[p.id]?.height>photos[p.id]?.width*1.15)image.classList.add('portrait-photo');image.append(picture(p,'',false),el('span','profile-photo-tag',p.country));visual.append(image);addCredit(p,visual);
    const mini=el('div','mini-map');if(window.MLL_MAP?.mini){const rendered=MLL_MAP.mini(p);if(typeof rendered==='string')mini.innerHTML=rendered;else if(rendered)mini.append(rendered);}else{mini.append(el('p','','📍 '+p.name+' · '+p.country));}mini.append(link('Find it on the world map ↗','#map?focus='+p.id,'mini-map-label'));visual.append(mini);
    if(p.familyStops){const stops=el('section','family-stops');stops.append(el('h3','','Your family trail'));p.familyStops.forEach(s=>stops.append(el('p','',s.name+', '+s.state+' — '+s.connection)));stops.append(link('See the family pins ↗','#map?filter=family','button small ghost'));visual.append(stops);}
    const copy=el('div','profile-copy');copy.append(el('p','eyebrow',p.family?'A PLACE IN YOUR STORY':p.country.toUpperCase()+' / DISCOVERY'),el('h1','',p.name),el('p','profile-hook',p.hook));if(p.familyNote)copy.append(el('p','family-note',p.familyNote));const facts=el('ol','fact-list');p.facts.forEach(f=>facts.append(el('li','',f)));copy.append(facts);const actions=el('div','learn-actions'),listen=button('◖ Listen','button small',()=>read(p.name+'. '+(p.familyNote||'')+' '+p.facts.join(' '),listen));actions.append(listen);const stamp=button(state.stamps.includes(p.id)?'✓ Passport stamped':'✦ Stamp my passport','button small stamp-button',()=>{if(state.stamps.includes(p.id)){toast('Already stamped. You can always come back!');return;}state.stamps.push(p.id);save();stamp.textContent='✓ Passport stamped';stamp.classList.add('collected');toast('✦ '+p.name+' added to your stamps!');});if(state.stamps.includes(p.id))stamp.classList.add('collected');actions.append(stamp);copy.append(actions,stretch(p),quiz(p),sources(p));
    const isMoscow=p.wikiTitle==='Moscow'||/moscow/i.test(p.id);if(isMoscow){const block=el('div','passport-strip');block.append(el('p','','Try fitting falling shapes into complete rows.'),link('Play Block Lab →','#blocks','button small'));copy.append(block);}grid.append(visual,copy);view.append(grid);const bottom=el('div','profile-bottom');bottom.append(link('Explore more places','#places','button ghost'),button('✦ Another surprise','button primary',surprise));view.append(bottom);
  }
  function mapPage(query){topNav();view.append(heading('THE WORLD IS YOUR CLASSROOM','Point. Tap. Explore.','Tap a pin to meet a place. Zoom in to separate nearby destinations.'));const host=el('div','world-map-host');view.append(host);const stops=family.flatMap(p=>(p.familyStops||[]).map(s=>({id:p.id,name:s.name+' · '+s.state,lat:s.lat,lon:s.lon,family:true,hook:s.connection})));if(window.MLL_MAP){dispose=MLL_MAP.mount(host,[...places,...stops],{onSelect:id=>{location.hash='place/'+id+'?from=map';},visited:new Set(state.visited)});const f=query.get('focus');if(f&&dispose?.focus)dispose.focus(f);if(query.get('filter')==='family')host.querySelector('[data-filter="family"]')?.click();}else host.append(el('p','error-note','The map could not load. You can still explore every place below.'));const info=el('div','passport-strip');info.append(el('p','','Surprise places appear in a shuffled order. Discover all '+surprises.length+' before the deck repeats.'),button('✦ Surprise me','button small primary',surprise));view.append(info);}
  function passport(){topNav();const h=heading('YOUR EXPLORER PASSPORT','Look where you’ve been.',state.stamps.length+' passport stamps · '+state.quiz.length+' questions explored');h.append(el('div','passport-stat',state.visited.length+' / '+places.length));view.append(h);const bar=el('div','passport-progress'),fill=el('span');fill.style.width=(100*state.visited.length/Math.max(1,places.length))+'%';bar.append(fill);bar.setAttribute('role','img');bar.setAttribute('aria-label',state.visited.length+' of '+places.length+' destinations discovered');view.append(bar);if(Object.keys(state.badges).length){const row=el('div','badges-row');Object.values(state.badges).forEach(t=>row.append(el('span','earned-badge','✦ '+t)));view.append(row);}if(!state.visited.length){const e=el('section','empty-state');e.append(el('h2','','Every adventure starts somewhere.'),el('p','','Open a place to start your passport. Come back here whenever you want to visit it again.'),button('Find my first surprise','button primary',surprise));view.append(e);return;}const grid=el('div','passport-grid');state.visited.slice().reverse().forEach(id=>grid.append(placeCard(byId.get(id),'passport')));view.append(grid);}
  function peopleMenu(){topNav();view.append(heading('BIG IDEAS START SMALL','Meet a curious mind.','Scientists, explorers, and artists all started by asking questions. Just like you.'));const grid=el('div','person-grid');people.forEach(p=>{const a=link('','#person/'+p.id,'person-card');const ph=photos[p.id];if(ph){const img=picture(p);img.className='person-card-photo';a.append(img);}else a.append(el('div','person-monogram',p.name.split(' ').map(x=>x[0]).join('')));a.append(el('span','person-year',p.role),el('h2','',p.name),el('p','',p.hook));grid.append(a);});view.append(grid);}
  function person(p){topNav('#people','← All curious minds');document.title=p.name+' · Big Ideas';const grid=el('div','profile-layout'),left=el('div');if(photos[p.id]){const im=el('div','profile-photo portrait-photo');im.append(picture(p,'',false));left.append(im);addCredit(p,left);}else{const poster=el('div','person-portrait');poster.append(el('strong','',p.name.split(' ').map(n=>n[0]).join('')),el('span','',p.role));left.append(poster);}const activity=el('section','quiz-card');activity.append(el('p','eyebrow','TRY IT YOURSELF'),el('h2','',p.activity.title),el('p','',p.activity.prompt));if(p.id==='frida-kahlo')activity.append(link('Open Pattern Studio →','#patterns','button'));if(p.id==='cousteau')activity.append(link('Meet ocean animals →','#ocean','button'));left.append(activity);const copy=el('div','profile-copy');copy.append(el('p','eyebrow',p.role.toUpperCase()),el('h1','',p.name),el('p','profile-hook',p.hook));const list=el('ol','fact-list');p.facts.forEach(t=>list.append(el('li','',t)));copy.append(list);const b=button('◖ Listen','button small',()=>read(p.name+'. '+p.facts.join(' '),b));copy.append(b,stretch(p),quiz(p),sources(p));grid.append(left,copy);view.append(grid);}
  function game(kind){const m=config.modules.find(m=>m.id===kind);view.classList.add('game-page');topNav();const container=el('div','game-container');view.append(container);if(window.MLL_GAMES){dispose=MLL_GAMES.mount(kind,container,{award,read,get:(key,fallback)=>state.games[key]??fallback,set:(key,value)=>{state.games[key]=value;save();}});}else container.append(el('p','error-note','This activity did not load. Go Home and try again.'));}
  function route(){routeToken++;stopReading();if(dispose){dispose();dispose=null;}view.className='';view.replaceChildren();const raw=location.hash.slice(1)||'home',parts=raw.split('?'),path=parts[0].split('/'),query=new URLSearchParams(parts[1]||'');const page=path[0];document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===(page==='place'?(query.get('from')==='map'?'map':'home'):page==='map'?'map':page==='passport'?'passport':'home');if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=state.name+"'s Learning Lab";
    if(page==='place'&&byId.has(path[1]))profile(byId.get(path[1]),query.get('from'));
    else if(page==='person'&&people.some(p=>p.id===path[1]))person(people.find(p=>p.id===path[1]));
    else if(page==='places')placeMenu();else if(page==='map')mapPage(query);else if(page==='passport')passport();else if(page==='people')peopleMenu();else if(['baseball','blocks','patterns','ocean'].includes(page))game(page);else home();
    window.scrollTo(0,0);view.focus({preventScroll:true});
  }
  let chosenBadge=state.badge;
  $('settings-button').addEventListener('click',()=>{$('explorer-name').value=state.name;chosenBadge=state.badge;const box=$('badge-choices');box.replaceChildren();config.badges.forEach(symbol=>{const b=button(symbol,'',()=>{chosenBadge=symbol;[...box.children].forEach(n=>n.setAttribute('aria-pressed',String(n===b)));});b.setAttribute('aria-label','Choose '+symbol+' badge');b.setAttribute('aria-pressed',String(symbol===chosenBadge));box.append(b);});$('settings-dialog').showModal();});
  $('save-settings').addEventListener('click',()=>{state.name=$('explorer-name').value.trim().slice(0,20)||'Max';state.badge=chosenBadge;save();route();});
  $('grownup-button').addEventListener('click',()=>{$('grownup-dialog').showModal();});$('close-grownup').addEventListener('click',()=>$('grownup-dialog').close());
  $('export-progress').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=link('',url);a.download='max-lab-progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  $('import-progress').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error();const incoming=JSON.parse(await file.text());if(incoming.version!==1||!Array.isArray(incoming.visited))throw new Error();state=normalize(incoming);save();$('grownup-dialog').close();route();toast('Your explorer passport is back.');}catch(err){toast('That file is not a Learning Lab progress backup.');}e.target.value='';});
  window.addEventListener('hashchange',route);window.addEventListener('pageshow',event=>{if(event.persisted)route();});window.addEventListener('pagehide',()=>{stopReading();if(dispose)dispose();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopReading();});
  updateHeader();route();
  // A small read-only handle makes content checks possible without altering progress.
  window.MLL_APP={places:places.map(p=>({id:p.id,name:p.name,family:!!p.family})),surpriseCount:surprises.length};
})();
